export const mainTheme = {
  token: { fontFamily: "__Poppins_199403, __Poppins_Fallback_199403" },
  components: {
    Form: {
      colorError: "#F5382C",
    },
    Checkbox: {
      colorPrimary: "#19363D",
      colorPrimaryHover: "#19363D",
    },
    Select: {
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 20,
      optionSelectedColor: "#F3F3F3",
      optionSelectedBg: "#19363D",
      optionActiveBg: "#19363D",
      optionActiveColor: "#F3F3F3",
      colorBorder: "#E6E7E6",
      colorBgElevated: "#F3F3F3",
      selectorBg: "#F3F3F3",
      colorText: "#0C0C0C",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
      // activeOutlineColor: "#D3EBE7",
      // activeBorderColor: "#D3EBE7",
      hoverBorderColor: "#D3EBE7",
    },
    DatePicker: {
      fontSize: 20,
      colorBorder: "rgb(0, 0, 0,0.5)",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#D3EBE7",
      colorBorderHover: "#D3EBE7",
      colorText: "#D3EBE7",
    },
    Table: {
      headerBg: "#b8c1c355",
      colorBgContainer: "#FDFDFD",
      colorText: "#0C0C0C",
      borderColor: "#DFE1E3",
      headerColor: "#0C0C0C",
      fontSize: 18,
      footerColor: "#FDFDFD",
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#0C0C0C",
    },
  },
};
